
server:
  port: 9123
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/bank?useSSL=false
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG

