
server:
  port: 9123
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:16199/auth/realms/oauth2-project/protocol/openid-connect/certs
  #http://127.0.0.1:16199/auth/realms/oauth2-project/.well-known/openid-configuration
  # generete the token & access the resource
#  curl --location --request POST 'http://127.0.0.1:16199/auth/realms/oauth2-project/protocol/openid-connect/token' \
#  --header 'Content-Type: application/x-www-form-urlencoded' \
#  --data-urlencode 'client_id=oauth2-app-api' \
#  --data-urlencode 'client_secret=f0d17596-783f-410e-a6ae-df344b82e0de' \
#  --data-urlencode 'scope=openid' \
#  --data-urlencode 'grant_type=client_credentials'
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/easy-bank?useSSL=false
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG



